### ISSUE TITLE
Broken links under "Support"

### ISSUE THREAD

**Issue by tobyink** [shlomif/HTML-Spelling-Site#2]
annocpan.org is gone. search.cpan.org just redirects to metacpan.org, and cpanratings.perl.org is on its way out.

(The above applies to most of your distributions, but filing the issue under HTML::Spelling::Site because it's the most recent release, and broken links in older releases are forgivable.)

**Comment by shlomif** [comment]
@tobyink : hi! This should be fixed in v0.4.3. Note that it is the nature of the WWW that links get broken: https://www.shlomifish.org/meta/FAQ/#broken_links . As a result I suggest you avoid filing such bugs in the future because they are annoying and require time to fix.
